name: build image and push image to dockerhub & ghcr.io

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  docker_ubuntu_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Reduce disk usage
        run: |
          bash .github/workflows/release_disk.sh
      - name: Build and push ubuntu 20.04 image
        uses: docker/build-push-action@v5.4.0
        with:
          file: ubuntu/20.04.Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository_owner }}/erlang_elixir_asdf_ubuntu:ubuntu2004
            ghcr.io/${{ github.repository_owner }}/erlang_elixir_asdf_ubuntu_container:ubuntu2004
      - name: Release disk usage
        run: |
          bash .github/workflows/release_disk.sh
      - name: Reduce latest build disk usage
        run: |
          bash .github/workflows/release_disk.sh
      - name: Build and push ubuntu 16.04 image
        uses: docker/build-push-action@v5.4.0
        with:
            file: ubuntu/16.04.Dockerfile
            context: .
            platforms: linux/amd64
            push: true
            tags: |
              ${{ github.repository_owner }}/erlang_elixir_asdf_ubuntu:ubuntu1604
              ghcr.io/${{ github.repository_owner }}/erlang_elixir_asdf_ubuntu_container:ubuntu1604
      - name: Release latest disk usage
        run: |
          bash .github/workflows/release_disk.sh
      - name: Build and push ubuntu 22.04 image
        uses: docker/build-push-action@v5.4.0
        with:
            file: ubuntu/22.04.Dockerfile
            context: .
            platforms: linux/amd64
            push: true
            tags: |
              ${{ github.repository_owner }}/erlang_elixir_asdf_ubuntu:latest
              ghcr.io/${{ github.repository_owner }}/erlang_elixir_asdf_ubuntu_container:latest
      - name: Release latest disk usage
        run: |
          bash .github/workflows/release_disk.sh