name: build image and push image to dockerhub & ghcr.io

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  docker_ubuntu_2004:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Reduce disk usage
        run: |
          echo "Before removing files:"
          sudo yes | docker system prune --force --all
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "After removing files:"
          df -mh
      - name: Build and push latest
        uses: docker/build-push-action@v5.4.0
        with:
          file: ubuntu/20.04.Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository_owner }}/erlang_elixir_asdf_ubuntu:ubuntu2004
            ghcr.io/${{ github.repository_owner }}/erlang_elixir_asdf_ubuntu_container:ubuntu2004
